name: Generate Dark Pac-Man Animation

on:
  schedule: # Execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Modify SVG for Dark Mode
        run: |
          sed -i 's/<svg /<svg style="background-color:#0d1117;" /' pacman-contribution-graph.svg
          sed -i 's/#ebedf0/#161b22/g' pacman-contribution-graph.svg  # Change light background to dark
          sed -i 's/#9be9a8/#39d353/g' pacman-contribution-graph.svg  # Adjust colors for dark mode

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
